// -----------------------------------------------------------------------------
// SrcGitignore.cpp                                             SrcGitignore.cpp
// -----------------------------------------------------------------------------
/**
 * @file
 * @brief      This file holds the implementation of the SrcGitignore class.
 * @author     Col. Walter E. Kurtz
 * @version    2018-05-03
 * @copyright  GNU General Public License - Version 3.0
 */

// -----------------------------------------------------------------------------
// Includes                                                             Includes
// -----------------------------------------------------------------------------
#include "SrcGitignore.h"


// -----------------------------------------------------------------------------
// Used namespaces                                               Used namespaces
// -----------------------------------------------------------------------------
using namespace std;


// -----------------------------------------------------------------------------
// Construction                                                     Construction
// -----------------------------------------------------------------------------

// ------------
// SrcGitignore
// ------------
/*
 *
 */
SrcGitignore::SrcGitignore()
{
  // nothing
}


// -----------------------------------------------------------------------------
// Setter methods                                                 Setter methods
// -----------------------------------------------------------------------------

// ---------
// setBinary
// ---------
/*
 *
 */
void SrcGitignore::setBinary(const string& name)
{
  m_binary = name;
}


// -----------------------------------------------------------------------------
// Getter methods                                                 Getter methods
// -----------------------------------------------------------------------------

// ---------
// getBinary
// ---------
/**
 *
 */
string SrcGitignore::getBinary() const
{
  return m_binary;
}


// -----------------------------------------------------------------------------
// Internal methods                                             Internal methods
// -----------------------------------------------------------------------------

// ----------
// printLines
// ----------
/*
 *
 */
void SrcGitignore::printLines(ofstream& target) const
{
  target << "# " << getLicense() << endl;
  target << endl;
  target << "# skip temporary g++ files" << endl;
  target << "*.d" << endl;
  target << "*.o" << endl;
  target << endl;
  target << "# skip html files generated by doxygen" << endl;
  target << "doc/html/" << endl;
  target << endl;
  target << "# skip final binary" << endl;
  target << getBinary() << endl;
}

